### ISSUE TITLE
Repository Private

### ISSUE THREAD

**Issue by BugelNiels** [jhugobb/CG#25]
Hi @jhugobb,

Could you please make this repository private? It seems that your repository contains solutions for the course Computer Graphics. Due to plagiarism issues, it is not allowed to host or share assignment solutions openly.

Cheers,
Niels

**Comment by jhugobb** [comment]
Hi @BugelNiels,

No problem, I will set it private. I had a great time with the course 5 years ago (and went on to complete a Master's in CG), and hope that future courses are just as good.
Apologies for any troubles it might have caused.

Hugo

**Comment by BugelNiels** [comment]
Really appreciate it! We are doing our best :)
